---
title: "ReactableStars"
author: "TK"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reactable)
library(scales)
```

## Reactable Table with Stars

###Import Data

```{r ImportData}
AllDefense <- read.csv('../data/AllDefense.csv')

#utilized this season's player comparisons
Player_comps <- read.csv('../data/player_comparisons.csv')

```


###Format Data
```{r FormatData}
colnames(AllDefense)[1] <- 'Player'
AllDefense$first_or_second[AllDefense$first_or_second == 2] = 1
AllDef_Grouped <- AllDefense %>% group_by(Player, playerID) %>% summarise(selections = sum(first_or_second))
Player_comps$pct_match <- percent(Player_comps$pct_match, 1)
```


###Build Reactable
Markelle Fultz used in place of inputSelection
```{r Reactable Table  results = 'asis'}

  tbl <-     reactable(
            SelectedPlayerComp <- Player_comps  %>%  filter(player_name == 'Markelle Fultz') %>%
                select(rank, neighbor_player_name, neighbor_player_id, pct_match) %>%
                mutate(all_defender = ifelse(neighbor_player_name %in% AllDef_Grouped$Player, AllDef_Grouped$selections, 0)),
            bordered = FALSE, 
            pagination = FALSE,
            highlight = TRUE,
            fullWidth = FALSE,
            class = "CompTable",
            defaultColDef = colDef(headerClass = "header", align = "left"),
            columns = list(
                neighbor_player_id = colDef(
                    name = "",
                    minWidth = 50,
                    cell = function(value, index) {
                        div(
                            img(
                                src = sprintf(paste("https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/", 
                                                    paste(value,".png", sep = ""), sep = "")),
                                height = '25px',
                                width = '40px',
                                style = "float:left"
                            )
                        )
                    },
                    maxWidth = 50
                ),
                rank = colDef(name = "Rk", maxWidth = 45,class = "table_contents"),
                neighbor_player_name = colDef(name = "Player",minWidth = 140,class = "table_contents"),
                pct_match = colDef(name = "Similarity Score",minWidth = 60, class = "table_contents"),
                all_defender = colDef(
                    name = 'All Def Selections',
                    cell = function(value) {
                        if (value == 0) {"\u2718"
                        }
                        else {paste("\u2605", toString(value))}
                    },
                    style = function(value) {
                        if (value == 0) {
                            color <- "#e00000"
                        } else {
                            color <- "#d4af37"
                        }
                        list(color = color, fontWeight = 'bold')
                    }
                )
            )
        )
        

tbl

```